=== ygojson/ygojson-tools/src/main/resources/schema/set.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "set.schema",
  "title": "Set Data Model",
  "javaType": "io.github.ygojson.model.data.Set",
  "description": "Describes the information for a set.\nThis model contains the properties of the set that will not change from print to print.\n",
  "type": "object",
  "properties": {
    "id": {
      "title": "UUID (v5) of the Set generated by YGOJSON",
      "type": "string",
      "format": "uuid"
    },
    "name": {
      "title": "Name of the Set",
      "type": "string"
    },
    "nameAlt": {
      "title": "Alternative name of the Set",
      "description": "Alternative name of the set for some special cases\n",
      "type": "string"
    },
    "setCode": {
      "title": "Set code",
      "description": "Code that appears on the print to identify that it belongs to the set.\n",
      "type": "string",
      "pattern": "[a-zA-Z0-9]+"
    },
    "setCodeAlt": {
      "title": "Alternative set code",
      "description": "Alternative set code for some special cases\n",
      "type": "string",
      "pattern": "[a-zA-Z0-9]+"
    },
    "printNumberPrefix": {
      "title": "Prefix for the printNumber",
      "description": "Special editions and/or promotional cards have a prefix to indicate that they are not from the original set.\nNote that for sub-sets (i.e., several decks on one set) also include a prefix on the printNumber but this doesn't identify the set",
      "type": "string"
    },
    "type": {
      "title": "Type of the Set (lower-case)",
      "type": "string",
      "pattern": "[a-z-0-9]+"
    },
    "series": {
      "title": "Series of the Set (lower-case)",
      "type": "string",
      "pattern": "[a-z-0-9]+"
    },
    "localizedData": {
      "title": "Localized Data for the Set",
      "$ref": "#/definitions/setLocalizedData"
    }
  },
  "required": [
    "id"
  ],
  "definitions": {
    "setInfo": {
      "title": "Set Information Definition Model",
      "description": "Set information that can be localized.\nThis model does not contain localized data for constant values.\n",
      "javaType": "io.github.ygojson.model.data.definition.SetInfo",
      "type": "object",
      "properties": {
        "name": {
          "title": "Name of the set",
          "type": "string"
        },
        "nameAlt": {
          "title": "Alternative name of the set",
          "description": "Alternative name of the set for some special cases\n",
          "type": "string"
        },
        "setCode": {
          "title": "Set code",
          "description": "Code that appears on the print to identify that it belongs to the set.\nNote that several products might have the same set assigned.\nAlso, some first-series set releases does not have a setCode assigned.\n",
          "type": "string",
          "pattern": "[a-zA-Z0-9]+"
        },
        "setCodeAlt": {
          "title": "Alternative set code",
          "description": "Alternative set code for some special cases\n",
          "type": "string",
          "pattern": "[a-zA-Z0-9]+"
        }
      }
    },
    "setLocalizedData": {
      "title": "SetLocalizedData",
      "javaType": "io.github.ygojson.model.data.definition.localization.SetLocalizedData",
      "type": "object",
      "properties": {
        "de": {
          "title": "German Translation",
          "$ref": "#/definitions/setInfo"
        },
        "es": {
          "title": "Spanish Translation",
          "$ref": "#/definitions/setInfo"
        },
        "fr": {
          "title": "French Translation",
          "$ref": "#/definitions/setInfo"
        },
        "it": {
          "title": "Italian Translation",
          "$ref": "#/definitions/setInfo"
        },
        "ja": {
          "title": "Japanese Translation",
          "$ref": "#/definitions/setInfo"
        },
        "ko": {
          "title": "Korean Translation",
          "$ref": "#/definitions/setInfo"
        },
        "pt": {
          "title": "Portuguese Translation",
          "$ref": "#/definitions/setInfo"
        },
        "zh-Hans": {
          "title": "Chinese Simplified Translation",
          "$ref": "#/definitions/setInfo"
        },
        "zh-Hant": {
          "title": "Chinese Traditional Translation",
          "$ref": "#/definitions/setInfo"
        }
      }
    }
  }
}

=== ygojson/ygojson-tools/model/src/test/resources/io/github/ygojson/model/utils/acceptancetest/SerializationAcceptanceTest.testDataModelSerialization.Set.approved.json
{
  "id" : "a09bd474-03e1-3314-8e13-ad9e06d17eee",
  "name" : "EEBEOAPEZS",
  "nameAlt" : "ZSPMQCXJT",
  "setCode" : "DYXKRPV",
  "setCodeAlt" : "WMMPMPYLW",
  "printNumberPrefix" : "KVMEOZG",
  "type" : "OQA",
  "series" : "HUFOJC",
  "localizedData" : {
    "de" : {
      "name" : "XGHP",
      "nameAlt" : "EQRGFN",
      "setCode" : "DJS",
      "setCodeAlt" : "GGWXHTNS"
    },
    "es" : {
      "name" : "CWAJI",
      "nameAlt" : "SNLZX",
      "setCode" : "FFLOPREZ",
      "setCodeAlt" : "TUKWWH"
    },
    "fr" : {
      "name" : "WXI",
      "nameAlt" : "ERRC",
      "setCode" : "TACUEFY",
      "setCodeAlt" : "KTXAF"
    },
    "it" : {
      "name" : "AXBDXLIXXD",
      "nameAlt" : "XHJCTSAL",
      "setCode" : "MGBCUSPZ",
      "setCodeAlt" : "IAVKADEXAB"
    },
    "ja" : {
      "name" : "IWXHQJB",
      "nameAlt" : "GYZ",
      "setCode" : "CCBEX",
      "setCodeAlt" : "PEDCT"
    },
    "ko" : {
      "name" : "MVZUMETFSA",
      "nameAlt" : "EGJUEPKGO",
      "setCode" : "XAU",
      "setCodeAlt" : "DBYFL"
    },
    "pt" : {
      "name" : "YCILHPTA",
      "nameAlt" : "OBMP",
      "setCode" : "DEGYRTKTC",
      "setCodeAlt" : "LQWLX"
    },
    "zh-Hans" : {
      "name" : "JPI",
      "nameAlt" : "CJARSZB",
      "setCode" : "UOJ",
      "setCodeAlt" : "IMCBOLZHE"
    },
    "zh-Hant" : {
      "name" : "RQJLB",
      "nameAlt" : "ORREPNH",
      "setCode" : "AGXQYGANB",
      "setCodeAlt" : "PTJTIZ"
    }
  }
}
