=== ygojson/ygojson-tools/model-utils/src/test/resources/io/github/ygojson/model/utils/schema/JsonSchemaGeneratorAcceptanceTest.testInlineDataSchemas.Card.received.json
{
  "$schema" : "https://json-schema.org/draft/2019-09/schema",
  "type" : "object",
  "properties" : {
    "id" : {
      "type" : "string",
      "format" : "uuid",
      "description" : "UID (v5) for the Card (atomic) generated by YGOJSON."
    },
    "identifiers" : {
      "allOf" : [ {
        "type" : "object",
        "properties" : {
          "konamiId" : {
            "type" : "integer",
            "description" : "ID on the <a href=\"https://www.db.yugioh-card.com/yugiohdb/\">Yu-Gi-Oh official database</a>.\n\nThe ID might not appear on the official database for some languages if it was not released yet on that location.\nAlso, cards might not have an ID if nor released at all."
          },
          "password" : {
            "type" : "integer",
            "description" : "Unique 8-digit number printed in the bottom of cards, which is the same in all languages and prints.\n\nNote that certain cards does not have a password."
          },
          "passwordAlt" : {
            "type" : "integer",
            "description" : "Unique 8-digit number printed in the bottom of different prints of a card on some special cases.\n\nExamples of these are the <em>Dark Magician (Arkana)</em> and the alternative art of <em>Polymerization</em>"
          },
          "yugipediaPageId" : {
            "type" : "integer",
            "description" : "Page ID on <a href=\"https://yugipedia.com\">Yugipedia</a>.\n\nThis ID can be used on the <a href=\"https://yugipedia.com/api.php\">Yugipedia API</a> as the <em>pageId</em> or <em>pageids</em> parameters."
          }
        },
        "description" : "Identifiers associated to the Card (atomic).\n\nThis model is a container of third-party IDs associated with the Card (atomic)."
      }, {
        "description" : "Identifiers associated to the card."
      } ]
    },
    "name" : {
      "type" : "string",
      "description" : "Name of the card"
    },
    "cardType" : {
      "allOf" : [ {
        "type" : "string",
        "enum" : [ "monster", "spell", "trap" ],
        "description" : "Enum values for the main card types."
      }, {
        "description" : "Main card type."
      } ]
    },
    "property" : {
      "type" : "string",
      "description" : "Special property for the spell or trap (lower-case).\n\nThese are the properties represented by the spell/trap icon.",
      "pattern" : "[a-z]+"
    },
    "effectText" : {
      "type" : "string",
      "description" : "Effect text for the card (empty for Normal Monsters).\n\nNote that the list of materials and pendulum effects are not included as they are part of their own property.\n"
    },
    "monsterTypes" : {
      "description" : "Array of lower-case values for the monster-type line.",
      "type" : "array",
      "items" : {
        "type" : "string",
        "pattern" : "[a-z]+"
      }
    },
    "flavorText" : {
      "type" : "string",
      "description" : "Flavor text on a normal monster.\n\nIf the monster is an effect monster, this would be empty."
    },
    "attribute" : {
      "type" : "string",
      "description" : "Attribute of the monster (lower case).\n\nIf the monster is an effect monster, this would be empty.",
      "pattern" : "[a-z]+"
    },
    "atk" : {
      "type" : "integer",
      "description" : "Actual ATK value.\n\nIf <tt>0</tt>, it can also be undefined.\nIn that case, the <tt>atkUndefined</tt> property would be equal to <tt>true</tt>.",
      "minimum" : 0
    },
    "atkUndefined" : {
      "type" : "boolean",
      "description" : "Flag indicating an undefined (<tt>?</tt>) ATK value."
    },
    "def" : {
      "type" : "integer",
      "description" : "Actual DEF value.\n\nIf <tt>0</tt>, it can also be undefined.\nIn that case, the <tt>defUndefined</tt> property would be equal to <tt>true</tt>.",
      "minimum" : 0
    },
    "defUndefined" : {
      "type" : "boolean",
      "description" : "Flag indicating an undefined (<tt>?</tt>) DEF value."
    },
    "level" : {
      "type" : "integer",
      "description" : "Level of the monster.",
      "minimum" : 0
    },
    "materials" : {
      "type" : "string",
      "description" : "Materials for extra-deck monsters as defined on the card-text."
    },
    "pendulumEffect" : {
      "type" : "string",
      "description" : "Effect of the Pendulum monster."
    },
    "pendulumScale" : {
      "type" : "integer",
      "description" : "Scale of the Pendulum monster.",
      "minimum" : 0
    },
    "linkRating" : {
      "type" : "integer",
      "description" : "Link rating of the link monster.",
      "minimum" : 0
    },
    "linkArrows" : {
      "description" : "Link arrows of the link monster.",
      "maxItems" : 8,
      "type" : "array",
      "items" : {
        "type" : "string",
        "enum" : [ "top-left", "top-center", "top-right", "middle-left", "middle-right", "bottom-left", "bottom-center", "bottom-right" ],
        "description" : "Enum values for the arrows on link monster."
      }
    },
    "xyzRank" : {
      "type" : "integer",
      "description" : "Rank of the XYZ monster.",
      "minimum" : 0
    },
    "localizedData" : {
      "type" : "object",
      "properties" : {
        "es" : {
          "type" : "object",
          "properties" : {
            "name" : {
              "type" : "string",
              "description" : "Name of the card"
            },
            "effectText" : {
              "type" : "string",
              "description" : "Effect text for the card (empty for Normal Monsters).\n\nNote that the list of materials and pendulum effects are not included as they are part of their own property.\n"
            },
            "flavorText" : {
              "type" : "string",
              "description" : "Flavor text on a normal monster.\n\nIf the monster is an effect monster, this would be empty."
            },
            "materials" : {
              "type" : "string",
              "description" : "Materials for extra-deck monsters as defined on the card-text."
            },
            "pendulumEffect" : {
              "type" : "string",
              "description" : "Effect of the Pendulum monster."
            }
          },
          "description" : "Describes card text that can be localized.\n\nOnly card information that is not an enum is included."
        },
        "ja" : {
          "type" : "object",
          "properties" : {
            "name" : {
              "type" : "string",
              "description" : "Name of the card"
            },
            "effectText" : {
              "type" : "string",
              "description" : "Effect text for the card (empty for Normal Monsters).\n\nNote that the list of materials and pendulum effects are not included as they are part of their own property.\n"
            },
            "flavorText" : {
              "type" : "string",
              "description" : "Flavor text on a normal monster.\n\nIf the monster is an effect monster, this would be empty."
            },
            "materials" : {
              "type" : "string",
              "description" : "Materials for extra-deck monsters as defined on the card-text."
            },
            "pendulumEffect" : {
              "type" : "string",
              "description" : "Effect of the Pendulum monster."
            }
          },
          "description" : "Describes card text that can be localized.\n\nOnly card information that is not an enum is included."
        }
      },
      "description" : "Describes translations and locale-specific data for a card.\n\nAll translated properties match the name of the original property\nand any missing property indicates no translation for it."
    }
  },
  "$id" : "io.github.ygojson.model.data.Card",
  "description" : "Describes the information for a card.\n\nThis model contains the properties of the card that will not change from print to print."
}

=== ygojson/ygojson-tools/src/test/resources/io/github/ygojson/acceptancetest/yugipedia/mapper/card/name_present.approved.json
{
  "identifiers" : {
    "konamiId" : 4428,
    "password" : 32809211,
    "yugipediaPageId" : 3497
  },
  "name" : "Jinzo #7",
  "cardType" : "monster",
  "effectText" : "This monster can attack your opponent's Life Points directly.",
  "monsterTypes" : [ "machine", "effect" ],
  "attribute" : "dark",
  "atk" : 500,
  "def" : 400,
  "level" : 2,
  "localizedData" : {
    "de" : {
      "name" : "Jinzo #7",
      "effectText" : "Diese Karte kann die Life Points deines Gegners direkt angreifen."
    },
    "es" : {
      "name" : "Jinzo #7",
      "effectText" : "Esta carta puede atacar los Life Points de tu adversario directamente."
    },
    "fr" : {
      "name" : "Jinzo N°7",
      "effectText" : "Ce monstre peut attaquer directement les Life Points de votre adversaire."
    },
    "it" : {
      "name" : "Jinzo #7",
      "effectText" : "Questo mostro può attaccare direttamente i Life Points del tuo avversario."
    },
    "ja" : {
      "name" : "<ruby>人<rt>じん</rt></ruby><ruby>造<rt>ぞう</rt></ruby><ruby>人<rt>にん</rt></ruby><ruby>間<rt>げん</rt></ruby>７<ruby>号<rt>ごう</rt></ruby>",
      "effectText" : "このカードは相手プレイヤーを直接攻撃する事ができる。"
    },
    "ko" : {
      "name" : "인조인간7호",
      "effectText" : "이 카드는 상대를 직접 공격할 수 있다."
    },
    "pt" : {
      "name" : "Jinzo Nº 7",
      "effectText" : "Esta carta pode atacar seu oponente diretamente."
    }
  }
}

=== ygojson/ygojson-tools/tools/src/test/resources/io/github/ygojson/tools/dataprovider/impl/yugipedia/acceptance/YugipediaCardMapper/spell.approved.json
{
  "identifiers" : {
    "konamiId" : 4342,
    "password" : 53129443,
    "yugipediaPageId" : 160
  },
  "name" : "Dark Hole",
  "cardType" : "spell",
  "property" : "normal",
  "effectText" : "Destroy all monsters on the field.",
  "localizedData" : {
    "de" : {
      "name" : "Schwarzes Loch",
      "effectText" : "Zerstöre alle Monster auf dem Spielfeld."
    },
    "es" : {
      "name" : "Agujero Oscuro",
      "effectText" : "Destruye todos los monstruos en el Campo."
    },
    "fr" : {
      "name" : "Trou Noir",
      "effectText" : "Détruisez tous les monstres sur le Terrain."
    },
    "it" : {
      "name" : "Buco Nero",
      "effectText" : "Distruggi tutti i mostri sul Terreno."
    },
    "ja" : {
      "name" : "ブラック・ホール",
      "effectText" : "①：フィールドのモンスターを全て破壊する。"
    },
    "ko" : {
      "name" : "블랙홀",
      "effectText" : "①: 필드의 몬스터를 전부 파괴한다."
    },
    "pt" : {
      "name" : "Buraco Negro",
      "effectText" : "Destrua todos os monstros no campo."
    },
    "zh-Hans" : {
      "name" : "黑洞",
      "effectText" : "①：将场上的怪兽全部破坏。"
    },
    "zh-Hant" : {
      "name" : "黑洞",
      "effectText" : "破坏场上的全部怪兽。"
    }
  }
}

=== ygojson/ygojson-tools/tools/src/test/resources/io/github/ygojson/tools/dataprovider/impl/yugipedia/acceptance/YugipediaCardMapper/pendulum_non_effect_monster.approved.json
{
  "identifiers" : {
    "konamiId" : 11353,
    "password" : 65518099,
    "yugipediaPageId" : 315900
  },
  "name" : "Qliphort Scout",
  "cardType" : "monster",
  "monsterTypes" : [ "machine", "pendulum" ],
  "flavorText" : "Booting in Replica Mode...\nAn error has occurred while executing C:\\sophia\\zefra.exe\nUnknown publisher.\nAllow C:\\tierra\\qliphort.exe ? <Y/N>...[Y]\nBooting in Autonomy Mode...",
  "attribute" : "earth",
  "atk" : 1000,
  "def" : 2800,
  "level" : 5,
  "pendulumEffect" : "You cannot Special Summon monsters, except \"Qli\" monsters. This effect cannot be negated. Once per turn: You can pay 800 LP; add 1 \"Qli\" card from your Deck to your hand, except \"Qliphort Scout\".",
  "pendulumScale" : 9,
  "localizedData" : {
    "de" : {
      "name" : "Qliphort-Kundschafter",
      "flavorText" : "Replika-Modus wird gebootet...\nFehler beim Ausführen von C:\\sophia\\zefra.exe\nUnbekannter Entwickler.\nC:\\tierra\\qliphort.exe zulassen? <J/N>...[J]\nAutonomie-Modus wird gebootet...",
      "pendulumEffect" : "Du kannst keine als Spezialbeschwörung beschwören, außer „Qli“-Monstern. Dieser Effekt kann nicht annulliert werden. Einmal pro Spielzug: Du kannst 800 LP zahlen; füge einer Hand 1 „Qli“-Karte von deinem Deck hinzu, außer „Qliphort-Kundschafter“."
    },
    "es" : {
      "name" : "Explorador Qlifuerte",
      "flavorText" : "Iníciando en Modo Réplica...\nOcurrió un error mientras se ejecutaba C:\\sophia\\zefra.exe\nEditor desconocido.\n¿Permitir ejecutar C:\\tierra\\qlifuerte.exe? &lt;S/N>.. [S]\nIníciando en Modo Autónomo...",
      "pendulumEffect" : "No puedes Invocar monstruos de Modo Especial, excepto monstruos \"Qli\". Este efecto no puede ser negado. Una vez por turno: puedes pagar 800 LP; añade a tu mano 1 carta \"Qli\" en tu Deck, excepto \"Explorador Qlifuerte\"."
    },
    "fr" : {
      "name" : "Sentinelle Qliphort",
      "flavorText" : "Démarrage en Mode Réplique...\nUne erreur est survenue lors de l’exécution de C:\\sophia\\zefra.exe\nÉditeur inconnu.\nAutoriser C:\\tierra\\qliphort.exe ? <O/N>...[O]\nDémarrage en Mode Autonomie...",
      "pendulumEffect" : "Vous ne pouvez pas Invoquer Spécialement de monstres (monstres \"Qli\" exclus). Cet effet ne peut pas être annulé. Une fois par tour : vous pouvez payer 800 LP ; ajoutez 1 carte \"Qli\" (\"Sentinelle Qliphort\" exclu) depuis votre Deck à votre main."
    },
    "it" : {
      "name" : "Scout Qliphort",
      "flavorText" : "Avvio in Modalità Replica...\nSi è verificato un errore durante l'esecuzione di C:\\sophia\\zefra.exe\nAutore sconosciuto.\nPermettere l'avvio di C:\\tierra\\qliphort.exe ? &lt;S/N>...[S]\nAvvio in Modalità Autonoma...",
      "pendulumEffect" : "Non puoi Evocare Specialmente mostri, eccetto mostri \"Qli\". Questo effetto non può essere annullato. Una volta per turno: puoi pagare 800 LP; aggiungi 1 carta \"Qli\" dal tuo Deck alla tua mano, eccetto \"Scout Qliphort\"."
    },
    "ja" : {
      "name" : "クリフォート・ツール",
      "flavorText" : "システムをレプリカモードで<ruby>起<rt>き</rt></ruby><ruby>動<rt>どう</rt></ruby>する<ruby>準<rt>じゅん</rt></ruby><ruby>備<rt>び</rt></ruby>をしています...\nC:¥sophia¥sefiroth.exe <ruby>実<rt>じっ</rt></ruby><ruby>行<rt>こう</rt></ruby><ruby>中<rt>ちゅう</rt></ruby>にエラーが<ruby>発<rt>はっ</rt></ruby><ruby>生<rt>せい</rt></ruby>しました。\n<ruby>次<rt>つぎ</rt></ruby>の<ruby>不<rt>ふ</rt></ruby><ruby>明<rt>めい</rt></ruby>な<ruby>発<rt>はっ</rt></ruby><ruby>行<rt>こう</rt></ruby><ruby>元<rt>もと</rt></ruby>からのファイルを<ruby>実<rt>じっ</rt></ruby><ruby>行<rt>こう</rt></ruby>しようとしています。\nC:¥tierra¥qliphoth.exe の<ruby>実<rt>じっ</rt></ruby><ruby>行<rt>こう</rt></ruby>を<ruby>許<rt>きょ</rt></ruby><ruby>可<rt>か</rt></ruby>しますか？ <Y/N>...[Y]\nシステムを<ruby>自<rt>じ</rt></ruby><ruby>立<rt>りつ</rt></ruby>モードで<ruby>起<rt>き</rt></ruby><ruby>動<rt>どう</rt></ruby>します。",
      "pendulumEffect" : "①：<ruby>自<rt>じ</rt></ruby><ruby>分<rt>ぶん</rt></ruby>は「クリフォート」モンスターしか<ruby>特<rt>とく</rt></ruby><ruby>殊<rt>しゅう</rt></ruby><ruby>召<rt>しょう</rt></ruby><ruby>喚<rt>かん</rt></ruby>できない。この<ruby>効<rt>こう</rt></ruby><ruby>果<rt>か</rt></ruby>は<ruby>無<rt>む</rt></ruby><ruby>効<rt>こう</rt></ruby><ruby>化<rt>か</rt></ruby>されない。②：１ターンに１<ruby>度<rt>ど</rt></ruby>、８００<ruby>ＬＰ<rt>ライフポイント</rt></ruby>を<ruby>払<rt>は</rt></ruby>って<ruby>発<rt>はつ</rt></ruby><ruby>動<rt>どう</rt></ruby>できる。デッキから「クリフォート・ツール」以外の「クリフォート」カード１枚を<ruby>手<rt>て</rt></ruby><ruby>札<rt>ふだ</rt></ruby>に<ruby>加<rt>くわ</rt></ruby>える。"
    },
    "ko" : {
      "name" : "클리포트 툴",
      "flavorText" : "시스템을 레플리카 모드로 기동할 준비를 하고 있습니다...\nC:₩sophia₩sefiroth.exe 실행중에 에러가 발생했습니다.\n다음의 알 수 없는 발행원으로부터의 프로그램을 실행하려고 합다.\nC:₩tierra₩qliphoth.exe의 실행을 허가하시겠습니까? <Y/N>...[Y]\n시스템을 자율 모드로 기동합니다.",
      "pendulumEffect" : "①: 자신은 \"클리포트\" 몬스터밖에 특수 소환할 수 없다. 이 효과는 무효화되지 않는다. ②: 1턴에 1번, 800 LP를 지불하고 발동할 수 있다. 덱에서 \"클리포트 툴\" 이외의 \"클리포트\" 카드 1장을 패에 넣는다."
    },
    "pt" : {
      "name" : "Batedor Qliphort",
      "flavorText" : "Reiniciando em Modo de Réplica...\nUm erro aconteceu ao executar C:\\sophia\\zefra.exe\nAutor desconhecido.\nPermitir C:\\tierra\\qliphort.exe ? &lt;S/N>...[S]\nReinciando em Modo Autônomo...",
      "pendulumEffect" : "Você não pode Invocar monstros por Invcação-Especial, exceto monstros \"Qli\". Este efeito não pode ser negado. Uma vez por turno: você pode pagar 800 PV; adicione 1 card \"Qli\" do seu Deck à sua mão, exceto \"Batedor Qliphort\"."
    }
  }
}
