=== ygojson/ygojson-tools/model-utils/src/test/resources/io/github/ygojson/model/utils/schema/acceptance/JsonSchemaGeneratorAcceptanceTest.testInlineDataSchemas.Card.approved.json
{
  "$schema" : "https://json-schema.org/draft/2019-09/schema",
  "type" : "object",
  "properties" : {
    "id" : {
      "type" : "string",
      "format" : "uuid"
    },
    "identifiers" : {
      "type" : "object",
      "properties" : {
        "konamiId" : {
          "type" : "integer"
        },
        "password" : {
          "type" : "integer"
        },
        "passwordAlt" : {
          "type" : "integer"
        },
        "yugipediaPageId" : {
          "type" : "integer"
        }
      }
    },
    "name" : {
      "type" : "string"
    },
    "cardType" : {
      "type" : "string",
      "enum" : [ "monster", "spell", "trap" ]
    },
    "property" : {
      "type" : "string",
      "pattern" : "[a-z]+"
    },
    "effectText" : {
      "type" : "string"
    },
    "monsterTypes" : {
      "type" : "array",
      "items" : {
        "type" : "string"
      }
    },
    "flavorText" : {
      "type" : "string"
    },
    "attribute" : {
      "type" : "string",
      "pattern" : "[a-z]+"
    },
    "atk" : {
      "type" : "integer",
      "minimum" : 0
    },
    "atkUndefined" : {
      "type" : "boolean"
    },
    "def" : {
      "type" : "integer",
      "minimum" : 0
    },
    "defUndefined" : {
      "type" : "boolean"
    },
    "level" : {
      "type" : "integer",
      "minimum" : 0
    },
    "materials" : {
      "type" : "string"
    },
    "pendulumEffect" : {
      "type" : "string"
    },
    "pendulumScale" : {
      "type" : "integer",
      "minimum" : 0
    },
    "linkRating" : {
      "type" : "integer",
      "minimum" : 0
    },
    "linkArrows" : {
      "maxItems" : 8,
      "type" : "array",
      "items" : {
        "type" : "string",
        "enum" : [ "top-left", "top-center", "top-right", "middle-left", "middle-right", "bottom-left", "bottom-center", "bottom-right" ]
      }
    },
    "xyzRank" : {
      "type" : "integer",
      "minimum" : 0
    },
    "localizedData" : {
      "type" : "object",
      "properties" : {
        "de" : {
          "type" : "object",
          "properties" : {
            "name" : {
              "type" : "string"
            },
            "effectText" : {
              "type" : "string"
            },
            "flavorText" : {
              "type" : "string"
            },
            "materials" : {
              "type" : "string"
            },
            "pendulumEffect" : {
              "type" : "string"
            }
          }
        },
        "es" : {
          "type" : "object",
          "properties" : {
            "name" : {
              "type" : "string"
            },
            "effectText" : {
              "type" : "string"
            },
            "flavorText" : {
              "type" : "string"
            },
            "materials" : {
              "type" : "string"
            },
            "pendulumEffect" : {
              "type" : "string"
            }
          }
        },
        "fr" : {
          "type" : "object",
          "properties" : {
            "name" : {
              "type" : "string"
            },
            "effectText" : {
              "type" : "string"
            },
            "flavorText" : {
              "type" : "string"
            },
            "materials" : {
              "type" : "string"
            },
            "pendulumEffect" : {
              "type" : "string"
            }
          }
        },
        "it" : {
          "type" : "object",
          "properties" : {
            "name" : {
              "type" : "string"
            },
            "effectText" : {
              "type" : "string"
            },
            "flavorText" : {
              "type" : "string"
            },
            "materials" : {
              "type" : "string"
            },
            "pendulumEffect" : {
              "type" : "string"
            }
          }
        },
        "ja" : {
          "type" : "object",
          "properties" : {
            "name" : {
              "type" : "string"
            },
            "effectText" : {
              "type" : "string"
            },
            "flavorText" : {
              "type" : "string"
            },
            "materials" : {
              "type" : "string"
            },
            "pendulumEffect" : {
              "type" : "string"
            }
          }
        },
        "ko" : {
          "type" : "object",
          "properties" : {
            "name" : {
              "type" : "string"
            },
            "effectText" : {
              "type" : "string"
            },
            "flavorText" : {
              "type" : "string"
            },
            "materials" : {
              "type" : "string"
            },
            "pendulumEffect" : {
              "type" : "string"
            }
          }
        },
        "pt" : {
          "type" : "object",
          "properties" : {
            "name" : {
              "type" : "string"
            },
            "effectText" : {
              "type" : "string"
            },
            "flavorText" : {
              "type" : "string"
            },
            "materials" : {
              "type" : "string"
            },
            "pendulumEffect" : {
              "type" : "string"
            }
          }
        },
        "zh-Hans" : {
          "type" : "object",
          "properties" : {
            "name" : {
              "type" : "string"
            },
            "effectText" : {
              "type" : "string"
            },
            "flavorText" : {
              "type" : "string"
            },
            "materials" : {
              "type" : "string"
            },
            "pendulumEffect" : {
              "type" : "string"
            }
          }
        },
        "zh-Hant" : {
          "type" : "object",
          "properties" : {
            "name" : {
              "type" : "string"
            },
            "effectText" : {
              "type" : "string"
            },
            "flavorText" : {
              "type" : "string"
            },
            "materials" : {
              "type" : "string"
            },
            "pendulumEffect" : {
              "type" : "string"
            }
          }
        }
      }
    }
  },
  "required" : [ "id" ],
  "$id" : "io.github.ygojson.model.data.Card"
}

=== ygojson/ygojson-tools/model-utils/src/test/resources/io/github/ygojson/model/utils/schema/acceptance/SerializationAcceptanceTest.testDataModelSerialization.Card.approved.json
{
  "id" : "095df4ca-7856-367e-bcc9-9f73ec33651f",
  "identifiers" : {
    "konamiId" : 6152,
    "password" : 5487,
    "passwordAlt" : 8684,
    "yugipediaPageId" : 4599
  },
  "name" : "AHJMYUWW",
  "cardType" : "monster",
  "property" : "YHUF",
  "effectText" : "RXNFMQGE",
  "monsterTypes" : [ "CMXGHPTEQR", "FNZDJSJ", "GWXH" ],
  "flavorText" : "BEOAPEZSDZ",
  "attribute" : "NSKCWAJIWS",
  "atk" : 1862733697,
  "atkUndefined" : true,
  "def" : 792093345,
  "defUndefined" : true,
  "level" : 587265665,
  "materials" : "PMQCXJT",
  "pendulumEffect" : "DYXKRPV",
  "pendulumScale" : 2038680715,
  "linkRating" : 901762941,
  "linkArrows" : [ "middle-left", "top-center" ],
  "xyzRank" : 828415870,
  "localizedData" : {
    "de" : {
      "name" : "XYPEDCTCM",
      "effectText" : "ZUMETFSA",
      "flavorText" : "EGJUEPKGO",
      "materials" : "XAU",
      "pendulumEffect" : "DBYFL"
    },
    "es" : {
      "name" : "CILHPTA",
      "effectText" : "OBMP",
      "flavorText" : "DEGYRTKTC",
      "materials" : "LQWLX",
      "pendulumEffect" : "JPI"
    },
    "it" : {
      "name" : "XIVE",
      "effectText" : "RCITACUEF",
      "flavorText" : "JKTXAF",
      "materials" : "AXBDXLIXXD",
      "pendulumEffect" : "XHJCTSAL"
    }
  }
}
