=== ygojson/ygojson-tools/model-utils/src/test/resources/io/github/ygojson/model/utils/schema/acceptance/JsonSchemaGeneratorAcceptanceTest.testWithDefsDataSchemas.Set.approved.json
{
  "$schema" : "https://json-schema.org/draft/2019-09/schema",
  "$defs" : {
    "SetLocalizedData" : {
      "type" : "object",
      "properties" : {
        "de" : {
          "$ref" : "#/$defs/SetText"
        },
        "es" : {
          "$ref" : "#/$defs/SetText"
        },
        "fr" : {
          "$ref" : "#/$defs/SetText"
        },
        "it" : {
          "$ref" : "#/$defs/SetText"
        },
        "ja" : {
          "$ref" : "#/$defs/SetText"
        },
        "ko" : {
          "$ref" : "#/$defs/SetText"
        },
        "pt" : {
          "$ref" : "#/$defs/SetText"
        },
        "zh-Hans" : {
          "$ref" : "#/$defs/SetText"
        },
        "zh-Hant" : {
          "$ref" : "#/$defs/SetText"
        }
      }
    },
    "SetText" : {
      "type" : "object",
      "properties" : {
        "prefix" : {
          "type" : "string",
          "pattern" : "[a-zA-Z0-9]+-[a-zA-Z0-9]+"
        },
        "name" : {
          "type" : "string"
        }
      }
    }
  },
  "type" : "object",
  "properties" : {
    "id" : {
      "type" : "string",
      "format" : "uuid"
    },
    "prefix" : {
      "type" : "string",
      "pattern" : "[a-zA-Z0-9]+-[a-zA-Z0-9]+"
    },
    "name" : {
      "type" : "string"
    },
    "type" : {
      "type" : "string",
      "pattern" : "[a-z-0-9]+"
    },
    "series" : {
      "type" : "string",
      "pattern" : "[a-z-0-9]+"
    },
    "localizedData" : {
      "$ref" : "#/$defs/SetLocalizedData"
    }
  },
  "required" : [ "id" ],
  "$id" : "io.github.ygojson.model.data.Set"
}

=== ygojson/ygojson-tools/model-utils/src/test/resources/io/github/ygojson/model/utils/schema/acceptance/SerializationAcceptanceTest.testDataModelSerialization.Set.approved.json
{
  "id" : "b38892d6-d204-3397-b598-f3d9d93273e1",
  "prefix" : "AHJMYUWW",
  "name" : "RXNFMQGE",
  "type" : "JTGD",
  "series" : "XKRPVMWMMP",
  "localizedData" : {
    "de" : {
      "prefix" : "HTNSKCWA",
      "name" : "IWSNLZXIFF"
    },
    "fr" : {
      "prefix" : "YHUF",
      "name" : "JCMX"
    },
    "ko" : {
      "prefix" : "LWRKVM",
      "name" : "OZGBO"
    }
  }
}
